site_name: Ping Identity DevOps
repo_name: pingidentity/pingidentity-devops-getting-started
repo_url: https://github.com/pingidentity/pingidentity-devops-getting-started
site_url: https://devops.pingidentity.com/
copyright: © Copyright 2021 Ping Identity
#google_analytics: ['UA-156953351-1', 'devops.pingidentity.com']
extra_css:
  - mkdocs/overrides/stylesheets/extra.css

theme:
  name: material
  custom_dir: docs/mkdocs/overrides
  favicon: images/favicon.png

  features:
    - navigation.tabs
    - instant

  palette:
    primary: indigo
    accent: blue

edit_uri: ""

markdown_extensions:
  - attr_list
  - pymdownx.emoji
  - admonition
  - codehilite
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.snippets
  - meta
  - toc:
      # insert a blank space before the character
      permalink: " ¶"

plugins:
  - search:
        separator: '[\s\-\.]+'
  - redirects:
     redirect_maps:
       deployment/deployPdgPap.md: "deployment/deployPazPap.md"

nav:
  - DevOps @ Ping:
      - Home: "readme.md"
      - Overview: "overview.md"
      - License: license.md
      - Disclaimer: disclaimer.md
      - Third-Party Software: 3rdPartySoftware.md
      - Contributing: contributing.md
  - Get Started:
      - Introduction: "getStarted/getStarted.md"
      - DevOps Registration: "getStarted/devopsRegistration.md"
      - Kubernetes and Helm Basics: getStarted/k8sHelmBasics.md
      - Local Kubernetes Cluster: getStarted/localK8sCluster.md
  - Deployment:
      - Introduction: "deployment/deploy.md"
      - 
      - Metrics/Logs - Splunk: "deployment/collectMetricsWithSplunk.md"
  - Release Notes:
      - Current: "releaseNotes/2107.md"
      - Version 2106: "releaseNotes/2106.md"
      - Version 2105: "releaseNotes/2105.md"
      - Version 2104: "releaseNotes/2104.md"
      - Version 2103: "releaseNotes/2103.md"
      - Version 2102: "releaseNotes/2102.md"
      - Version 2101: "releaseNotes/2101.md"
      - Version 2012: "releaseNotes/2012.md"
      - Version 2011: "releaseNotes/2011.md"
      - Version 2010: "releaseNotes/2010.md"
      - Version 2009: "releaseNotes/2009.md"
      - Version 2008: "releaseNotes/2008.md"
      - Version 2007: "releaseNotes/2007.md"
      - Version 2006: "releaseNotes/2006.md"
      - Version 2005: "releaseNotes/2005.md"
      - Version 2004: "releaseNotes/2004.md"
      - Version 2003: "releaseNotes/2003.md"
