site_name: Ping Identity DevOps
repo_name: pingidentity/pingidentity-devops-getting-started
repo_url: https://github.com/pingidentity/pingidentity-devops-getting-started
site_url: https://devops.pingidentity.com/
copyright: © Copyright 2021 Ping Identity
#google_analytics: ['UA-156953351-1', 'devops.pingidentity.com']
extra_css:
  - mkdocs/overrides/stylesheets/extra.css

theme:
  name: material
  custom_dir: docs/mkdocs/overrides
  favicon: images/favicon.png

  features:
    - navigation.tabs
    - instant

  palette:
    primary: indigo
    accent: blue

edit_uri: ""

markdown_extensions:
  - attr_list
  - pymdownx.emoji
  - admonition
  - codehilite
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - meta
  - toc:
      # insert a blank space before the character
      permalink: " ¶"

plugins:
  - search:
        separator: '[\s\-\.]+'
  - redirects:
     redirect_maps:
       deployment/deployPdgPap.md: "deployment/deployPazPap.md"

nav:
  - DevOps @ Ping:
      - Home: "readme.md"
      - Overview: "overview.md"
      - License: license.md
      - Disclaimer: disclaimer.md
      - Third-Party Software: 3rdPartySoftware.md
      - Contributing: contributing.md
  - Release Notes:
      - Current: "release-notes/relnotes-2107.md"
      - Version 2106: "release-notes/relnotes-2106.md"
      - Version 2105: "release-notes/relnotes-2105.md"
      - Version 2104: "release-notes/relnotes-2104.md"
      - Version 2103: "release-notes/relnotes-2103.md"
      - Version 2102: "release-notes/relnotes-2102.md"
      - Version 2101: "release-notes/relnotes-2101.md"
      - Version 2012: "release-notes/relnotes-2012.md"
      - Version 2011: "release-notes/relnotes-2011.md"
      - Version 2010: "release-notes/relnotes-2010.md"
      - Version 2009: "release-notes/relnotes-2009.md"
      - Version 2008: "release-notes/relnotes-2008.md"
      - Version 2007: "release-notes/relnotes-2007.md"
      - Version 2006: "release-notes/relnotes-2006.md"
      - Version 2005: "release-notes/relnotes-2005.md"
      - Version 2004: "release-notes/relnotes-2004.md"
      - Version 2003: "release-notes/relnotes-2003.md"
